#!/bin/sh
# Copyright (C) 2010,2011,2014,2015,2016 The ESPResSo project
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
if test -n "$PYTHONPATH"; then
    PYTHONPATH=$PYTHONPATH:/home/itvms/PHD/CODING_DAY_20160316/espresso
else
    PYTHONPATH=/home/itvms/PHD/CODING_DAY_20160316/espresso
fi
export PYTHONPATH
exec /usr/bin/python $@
